### ISSUE TITLE
can this be used to crack WeChat on PC?

### ISSUE THREAD

**Issue by zhangzhxa** [chg-hou/EnMicroMsg.db-Password-Cracker#2]
I am using this to crack my WeChat on PC,and It runs 36 hours so far.
does it work for PC?
and if I get the pass how should I do in the next step？
you said Use the wonderful  wechat-dump written by Yuxin Wu,
but I saw his ,and don't know how to do?

**Comment by chg-hou** [comment]
Tested with the latest PC version and apparently it uses different password (or different encryption algorithm, not confirmed). So the answer to your first question is "not sure".
As no one have reported encryption details of the PC one, the best strategy might be recovering your db from PC to an Android phone and then extracting the android version db.

After having the correct password, just replace [Line 43 of decrypt-db.py](https://github.com/ppwwyyxx/wechat-dump/blob/master/decrypt-db.py#L43) with `key = '0123456'` (use your password instead of 0123456) and follow the steps in wechat-dump.
