### ISSUE TITLE
which openssl you used，i got the correct key by using IMEI and uin，but...

### ISSUE THREAD

**Issue by bixiu** [chg-hou/EnMicroMsg.db-Password-Cracker#3]
which openssl you used，i got the correct key by using IMEI and uin，but...when i try use this to decrpt the database,there are also can not open the database. i wonder if i do not use the correct openssl, thank you

**Comment by chg-hou** [comment]
@bixiu 
It's openssl 1.0.2.g. By the way, I don't think it's due to openssl, unless you used a quite old version. 
You could double-check with the provided [EnMicroMsg.db](https://github.com/chg-hou/EnMicroMsg.db-Password-Cracker/blob/master/EnMicroMsg.db) (key: '00001ef' ). If your complied password_cracker.o could crack it, everything goes well.

**Comment by bixiu** [comment]
i use openssl 1.0.1e,and i complie sqlcipher- windows with this successfully. i can open this  EnMicroMsg.db with key(00001ef) in sqlcipher browser(V2.1). but when i use the key to try to crack ,there is not correct.and i do not use py just compile password_cracker.c

**Comment by chg-hou** [comment]
@bixiu 
I have never test the codes with windows. Honestly, I don't know much about the changes from 1.0.1 to 1.0.2. As it depends on a lot of variables (mingw or cgwin, compiler version and settings), it is also hard to reproduce your problem with only openssl version provided. Of course,  you could debug the problem and check the output line by line. 
My suggestion would be trying the codes in a virtual machine with linux installed. It could be much faster and easier than struggling with windows.

**Comment by bixiu** [comment]
@chg-hou fine，thank you
